### PR TITLE
Fix future timeout issue

### LINKED ISSUE #404: Streaming job hangs at com.microsoft.azure.eventhubs.impl.ReactorDispatcher.signalWorkQueue(
- Info about the job:
The spark streaming job consume an eventhub and the batch interval is 5 minutes, after about 1 day's running.
In one of the stage, all executors finished except one hangs, the thread dump of the executor shows there are 16 threads in a "BLOCKED" state, which isn't seen in other executors, below is one of that. 

Thread ID | Thread Name | Thread State ▴ | Thread Locks
-- | -- | -- | --
11668 | ForkJoinPool-1-worker-1 | BLOCKED | Blocked by Thread Some(11665) Lock(java.lang.Object@1452782745})
sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:159) com.microsoft.azure.eventhubs.impl.ReactorDispatcher.signalWorkQueue(ReactorDispatcher.java:87) com.microsoft.azure.eventhubs.impl.ReactorDispatcher.invoke(ReactorDispatcher.java:60) com.microsoft.azure.eventhubs.impl.MessagingFactory.scheduleOnReactorThread(MessagingFactory.java:375) com.microsoft.azure.eventhubs.impl.MessageReceiver.receive(MessageReceiver.java:268) com.microsoft.azure.eventhubs.impl.PartitionReceiverImpl.receive(PartitionReceiverImpl.java:142) org.apache.spark.eventhubs.client.CachedEventHubsReceiver$$anonfun$org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receiveOne$1$$anonfun$apply$1.apply(CachedEventHubsReceiver.scala:90) org.apache.spark.eventhubs.client.CachedEventHubsReceiver$$anonfun$org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receiveOne$1$$anonfun$apply$1.apply(CachedEventHubsReceiver.scala:90) org.apache.spark.eventhubs.utils.RetryUtils$$anonfun$retryJava$1.apply(RetryUtils.scala:90) org.apache.spark.eventhubs.utils.RetryUtils$$anonfun$retryJava$1.apply(RetryUtils.scala:90) org.apache.spark.eventhubs.utils.RetryUtils$.org$apache$spark$eventhubs$utils$RetryUtils$$retryHelper$1(RetryUtils.scala:112) org.apache.spark.eventhubs.utils.RetryUtils$.retryScala(RetryUtils.scala:135) org.apache.spark.eventhubs.utils.RetryUtils$.retryJava(RetryUtils.scala:90) org.apache.spark.eventhubs.utils.RetryUtils$.retryNotNull(RetryUtils.scala:151) org.apache.spark.eventhubs.client.CachedEventHubsReceiver$$anonfun$org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receiveOne$1.apply(CachedEventHubsReceiver.scala:90) org.apache.spark.eventhubs.client.CachedEventHubsReceiver$$anonfun$org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receiveOne$1.apply(CachedEventHubsReceiver.scala:89) scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253) scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

let me know if you need the full thread dump.

- Spark version
2.3.0 (with Azure HDInsight 3.6)
- spark-eventhubs artifactId and version
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-eventhubs-spark_2.11</artifactId>
            <version>2.3.4</version>
        </dependency>

### LINKED ISSUE #411: Structured stream from event hub error: java.util.concurrent.TimeoutException: Futures timed out after
Databricks runtime:  4.3 (includes Apache Spark 2.3.1, Scala 2.11)
azure-eventhubs-spark_2.11-2.3.6

If only one message is sent to to azure event hub stream is stopped after a while with the following error:
java.util.concurrent.TimeoutException: Futures timed out after [300 seconds]
Table "intraday.trades" is not updated.

Sending more messages works most of the time.  But we need to reliably send and receive any number of messages. Please help. Thanks!

val customEventhubParameters = EventHubsConf(connectionString).setStartingPosition(EventPosition.fromEnqueuedTime(Instant.now))

intradayTrades.writeStream.format("delta").outputMode("append").option("mergeSchema", "true").option("checkpointLocation", s"$datalake$check").table("intraday.trades")

### LINKED ISSUE #413: Not able to iterate messages and java.util.concurrent.TimeoutException: Futures timed out after [300 seconds]
Not able to iterate the received message from EventHub. Below is the code sample.

```
val connString25Partition = ConnectionStringBuilder()
      .setNamespaceName("namespace")
      .setEventHubName("name")
      .setSasKeyName("policy")
      .setSasKey("key")
      .build

    val ehConf = EventHubsConf(connString25Partition)
      .setConsumerGroup("$Default")
      .setMaxEventsPerTrigger(5)
      .setStartingPosition(org.apache.spark.eventhubs.EventPosition.fromStartOfStream)

    val eventHubsStream = EventHubsUtils.createDirectStream(streamingContext,ehConf)
```

 case class EventContent(EventDetails: String)
  ```
eventHubsStream.map(x => EventContent(new String(x.getBytes)))
      .foreachRDD{ rdd =>
        logGeneral.info(f"rdd count = ${rdd.count()}")
        logGeneral.info(f" : rdd partition = ${rdd.getNumPartitions}")
        logGeneral.info(f" rdd vals ${rdd.take(5).foreach(println)}")
        rdd.foreach { message =>{
          logGeneral.info(s"inside foreach ==============")
            printMessage(message.EventDetails,"1")
          }
        }
      }
```

Able to print rdd count and partition count.
When we apply any action or tried to iterate rdd not workig.
We suspect there is no bound to EventData for this version.

> Let us know how we can iterate and print/excess the received message(EventData)

dependencies : 
<properties>
        <encoding>UTF-8</encoding>
        <scala.version>2.11.8</scala.version>
        <scala.compat.version>2.11</scala.compat.version>
        <spark.version>2.2.0</spark.version>
    </properties>
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-eventhubs-spark_2.11</artifactId>
            <version>2.3.6</version>
</dependency>

**Main issue : getting time out exception after few minutes : **

18/11/23 08:37:03 WARN TaskSetManager: Lost task 3.3 in stage 2.0 (TID 32, wn528-cpedev.uvjbok3wwvduho2dvkd4zdcj1e.bx.internal.cloudapp.net, executor 6): java.util.concurrent.TimeoutException: Futures timed out after [300 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.checkCursor(CachedEventHubsReceiver.scala:96)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receive(CachedEventHubsReceiver.scala:130)
	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver$.receive(CachedEventHubsReceiver.scala:179)
	at org.apache.spark.eventhubs.rdd.EventHubsRDD.compute(EventHubsRDD.scala:122)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by sjkwak**
The change addresses future timeout issue (#413, #411) and  dispatch signaling issue (#404).

close #413 
close #411 
close #404

### CODE REVIEW

File: core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala [hunk 1]
```diff
@@ -238,20 +242,31 @@ private[spark] class EventHubsClient(private val ehConf: EventHubsConf)
...
-                retryNotNull(r.receive(1), "translate: receive call")
-              }
-              .map { e =>
-                e.iterator.next.getSystemProperties.getSequenceNumber
+            val runtimeInfo =
+              Await.result(getRunTimeInfoF(nAndP.partitionId), ehConf.internalOperationTimeout)
+            val seqNo =
+              if (runtimeInfo.getIsEmpty || (pos.enqueuedTime != null &&
+                  runtimeInfo.getLastEnqueuedTimeUtc.isBefore(pos.enqueuedTime.toInstant))) {
+                latestSeqNoF(nAndP.partitionId)
```
Comment (sabeegrewal) [inline core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala]: Is `latestSeqNo` already available in `runtimeInfo`?

Comment (sjkwak) [reply core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala]: good catch, yes, we can get it from the runtimeInfo.
