### PR TITLE
Fix EventdataPosition to sequenceNumber translator to account for EndOfStream - idle partition cases

### LINKED ISSUE #254: Hit assertion while running a job on a brand new eventhub partition or EndOfStream
Hit this assertion: when I ran the spark job against a brand new eventhub with NO data. 
This is a one-off scenario and I think customer will very rarely, if not never, run into this.

SPARK adapter hits this assertion while trying to build begin and end seqno’s out of the Partitions and since the EventHub is brand new – it builds zero results.

```
java.lang.AssertionError: assertion failed: translate: result size 0 does not equal partition count 32
at scala.Predef$.assert(Predef.scala:170) at org.apache.spark.eventhubs.client.EventHubsClient.translate(EventHubsClient.scala:248) at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$initialPartitionSeqNos$1.apply(EventHubsSource.scala:103) at org.apache.spark.sql.eventhubs.EventHubsSource$$anonfun$initialPartitionSeqNos$1.apply(EventHubsSource.scala:101) at scala.Option.getOrElse(Option.scala:121) at org.apache.spark.sql.eventhubs.EventHubsSource.initialPartitionSeqNos$lzycompute(EventHubsSource.scala:101) at org.apache.spark.sql.eventhubs.EventHubsSource.initialPartitionSeqNos(EventHubsSource.scala:68) at org.apache.spark.sql.eventhubs.EventHubsSource.getOffset(EventHubsSource.scala:123) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268) at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:306) at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:60) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:267) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:264) at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) at scala.collection.AbstractTraversable.map(Traversable.scala:104) at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch(MicroBatchExecution.scala:264) at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$populateStartOffsets(MicroBatchExecution.scala:237) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:124) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121) at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:306) at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:60) at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:121) at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56) at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:117) at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:291) at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:201)
```

### PR DESCRIPTION
**Pull request by SreeramGarlapati**
Close #254 

published this to get a general sense of direction check...

Pending work:
1) find that begin sequence number is it 1L or 0L
2) scrub usage of DefaultConsumerGroup in that file to use the consumergroup provided by user.

### CODE REVIEW

File: core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala [hunk 1]
```diff
@@ -227,14 +226,34 @@ private[spark] class EventHubsClient(private val ehConf: EventHubsConf)
...
+            val receiverOptions = new ReceiverOptions()
+            receiverOptions.setReceiverRuntimeMetricEnabled(true)
+            val newReceiver = client
+              .createReceiverSync(DefaultConsumerGroup,
+                            partitionId.toString,
+                            com.microsoft.azure.eventhubs.EventPosition.fromStartOfStream,
+                            receiverOptions);
+            val startEvents = newReceiver.receiveSync(1)
+            if (startEvents == null || !startEvents.iterator().hasNext) {
+              result.put(partitionId, 1L);
```
Comment (sabeegrewal) [inline core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala]: Change to `0L`

File: core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala [hunk 2]
```diff
@@ -227,14 +226,34 @@ private[spark] class EventHubsClient(private val ehConf: EventHubsConf)
...
+            } else {
+              val lastSequenceNumber = newReceiver.getRuntimeInformation.getLastEnqueuedSequenceNumber
+              result.put(partitionId, lastSequenceNumber)
```
Comment (sabeegrewal) [inline core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala]: Change to `lastSequenceNumber + 1`

File: core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala (hunk 1 above)
Comment (SreeramGarlapati) [reply core/src/main/scala/org/apache/spark/eventhubs/client/EventHubsClient.scala]: actually wanted to run and findout.
